kind: Deployment
apiVersion: apps/v1
metadata:
  name: m1
spec:
  replicas: 3
  selector:
    matchLabels:
      name: test
  template:
    metadata:
      name: test
      labels:
        name : test
    spec:
      containers:
        - name: product
          image: jenkins/jenkins


